const tieflingHornShapes = [
	'Breit, an der Basis verbunden, nach außen und leicht nach oben gebogen',
	'Breit, massiv, an der Basis verbunden, nach außen und leicht nach oben gebogen',
	'Dick, gebogen, nach hinten gerichtet, fast halbkreisförmig',
	'Dick, massiv, nach außen und leicht nach oben gebogen',
	'Groß, weit auseinanderstehend, an der Basis verbunden, bilden eine Art "Helm"',
	'Klein, dünn, gerade nach oben gerichtet',
	'Klein, kräftig, leicht nach hinten gerichtet',
	'Klein, spitz, gerade, nach oben gerichtet',
	'Kurz, dick, nach hinten gebogen',
	'Kurz, gerade, eng beieinander, nach oben gerichtet, leicht gekrümmt',
	'Kurz, gerade, leicht nach hinten gebogen, breite Basis',
	'Kurz, gerade, spitz zulaufend',
	'Kurz, kräftig, leicht nach hinten gebogen',
	'Kurz, kräftig, nach hinten gebogen',
	'Kurz, leicht gebogen, nach oben gerichtet',
	'Kurz, nach außen und hinten gebogen',
	'Kurz, nach hinten gebogen, spitze',
	'Kurz, nach oben und dann scharf nach hinten gebogen, wie Haken',
	'Kurz, schlank, gerade, nach oben gerichtet',
	'Kurz, schlank, gerade',
	'Kurz, schlank, spitz, gerade nach oben gerichtet',
	'Kurz, spitz, gerade nach oben gerichtet',
	'Kurz, spitz, gerade, nach oben gerichtet',
	'Kurz, spitz, leicht gebogen',
	'Kurz, spitz, nach hinten gebogen',
	'Kurz, spitz, nach oben gerichtet',
	'Kürzer, massiv, nach hinten gerichtet',
	'Lang, dünn, gerade, leicht nach hinten geneigt',
	'Lang, dünn, leicht nach hinten gebogen, gerade',
	'Lang, dünn, leicht nach hinten gebogen',
	'Lang, gerade, scharf, fast parallel',
	'Lang, gerade, spitz zulaufend, leicht nach hinten gerichtet',
	'Lang, leicht gebogen, nach oben gerichtet',
	'Lang, leicht gedreht, nach hinten und außen gerichtet',
	'Lang, leicht geschwungen, nach hinten gerichtet',
	'Lang, lyraförmig, elegant nach außen und innen gebogen',
	'Lang, nach hinten gebogen, leicht gedreht',
	'Lang, nach hinten geschwungen, leicht gedreht',
	'Lang, spiralförmig, leicht nach hinten gebogen',
	'Lang, spiralförmig, mehrfach gedreht, elegant geschwungen',
	'Lyraförmig, elegant nach außen und innen gebogen',
	'Lyraförmig, scharfe Kurve nach außen und innen',
	'Lyraförmig, schlank, spitz zulaufend',
	'Lyraförmig, stark nach außen und innen gebogen',
	'Massiv, nach oben gerichtet, gekrümmt, rund im Querschnitt',
	'Nach oben, leicht nach außen und hinten gebogen',
	'Nach oben, leicht nach innen gebogen',
	'Relativ kurz, gebogen, nach hinten gerichtet',
	'Relativ kurz, leicht gedreht, nach oben gerichtet, leicht durchscheinend',
	'Schlank, nach hinten gebogen, leicht gedreht',
	'S-förmig geschwungen, scharfe Kurve nach innen',
	'Spiralförmig, dick, nach hinten gedreht',
	'Spiralförmig, nach hinten gerichtet',
	'Spiralig gedreht oder stark geschwungen, massiv, nach hinten gerichtet',
	'Stark gedreht, schraubenförmig, charakteristisches Korkenzieher-Muster',
	'Weit auseinander, flach, sichelförmig, leicht nach hinten gebogen',
];
